/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * API description
 * OpenAPI spec version: 1.0
 */
export interface CreateUrlDto {
  originalUrl: string;
  /**
   * @minLength 3
   * @maxLength 50
   */
  customCode?: string;
  /** @maxLength 200 */
  title?: string;
  /** @maxLength 500 */
  description?: string;
  /**
   * @minLength 4
   * @maxLength 100
   */
  password?: string;
  expiresAt?: string;
}

export interface UrlDto {
  id: string;
  code?: string;
  originalUrl: string;
  title?: string;
  description?: string;
  expiresAt?: string;
  createdAt: string;
  updatedAt: string;
  userId?: string;
  passwordHash: string;
}

/**
 * @nullable
 */
export type HealthControllerCheckLiveness200Info = {
  [key: string]: {
    status: string;
    [key: string]: unknown;
  };
} | null;

/**
 * @nullable
 */
export type HealthControllerCheckLiveness200Error = {
  [key: string]: {
    status: string;
    [key: string]: unknown;
  };
} | null;

export type HealthControllerCheckLiveness200Details = {
  [key: string]: {
    status: string;
    [key: string]: unknown;
  };
};

export type HealthControllerCheckLiveness200 = {
  status?: string;
  /** @nullable */
  info?: HealthControllerCheckLiveness200Info;
  /** @nullable */
  error?: HealthControllerCheckLiveness200Error;
  details?: HealthControllerCheckLiveness200Details;
};

/**
 * @nullable
 */
export type HealthControllerCheckLiveness503Info = {
  [key: string]: {
    status: string;
    [key: string]: unknown;
  };
} | null;

/**
 * @nullable
 */
export type HealthControllerCheckLiveness503Error = {
  [key: string]: {
    status: string;
    [key: string]: unknown;
  };
} | null;

export type HealthControllerCheckLiveness503Details = {
  [key: string]: {
    status: string;
    [key: string]: unknown;
  };
};

export type HealthControllerCheckLiveness503 = {
  status?: string;
  /** @nullable */
  info?: HealthControllerCheckLiveness503Info;
  /** @nullable */
  error?: HealthControllerCheckLiveness503Error;
  details?: HealthControllerCheckLiveness503Details;
};
