/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * API description
 * OpenAPI spec version: 1.0
 */
export interface CreateUrlDto {
  originalUrl: string;
  /**
   * @minLength 3
   * @maxLength 50
   */
  customCode?: string;
  /** @maxLength 200 */
  title?: string;
  /** @maxLength 500 */
  description?: string;
  /**
   * @minLength 4
   * @maxLength 100
   */
  password?: string;
  expiresAt?: string;
}

export interface UrlDto {
  id: string;
  code?: string;
  originalUrl: string;
  title?: string;
  description?: string;
  expiresAt?: string;
  createdAt: string;
  updatedAt: string;
  userId?: string;
  passwordHash: string;
}

/**
 * @nullable
 */
export type CheckLiveness200Info = {[key: string]: {
  status: string;
  [key: string]: unknown;
 }} | null;

/**
 * @nullable
 */
export type CheckLiveness200Error = {[key: string]: {
  status: string;
  [key: string]: unknown;
 }} | null;

export type CheckLiveness200Details = {[key: string]: {
  status: string;
  [key: string]: unknown;
 }};

export type CheckLiveness200 = {
  status?: string;
  /** @nullable */
  info?: CheckLiveness200Info;
  /** @nullable */
  error?: CheckLiveness200Error;
  details?: CheckLiveness200Details;
};

/**
 * @nullable
 */
export type CheckLiveness503Info = {[key: string]: {
  status: string;
  [key: string]: unknown;
 }} | null;

/**
 * @nullable
 */
export type CheckLiveness503Error = {[key: string]: {
  status: string;
  [key: string]: unknown;
 }} | null;

export type CheckLiveness503Details = {[key: string]: {
  status: string;
  [key: string]: unknown;
 }};

export type CheckLiveness503 = {
  status?: string;
  /** @nullable */
  info?: CheckLiveness503Info;
  /** @nullable */
  error?: CheckLiveness503Error;
  details?: CheckLiveness503Details;
};

