kind: pipeline
name: production-deploy

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: build-api
    image: docker
    environment:
      API_ENV_FILE:
        from_secret: API_ENV_FILE
    commands:
      - export TAG=${DRONE_COMMIT_SHA}
      - docker build -t localhost:5000/snapit-api:${TAG} -f apps/api/Dockerfile apps/api --build-arg BUILDKIT_INLINE_CACHE=1
      - docker push localhost:5000/snapit-api:${TAG}

  - name: build-web
    image: docker
    environment:
      WEB_ENV_FILE:
        from_secret: WEB_ENV_FILE
    commands:
      - export TAG=${DRONE_COMMIT_SHA}
      - docker build -t localhost:5000/snapit-web:${TAG} -f apps/web/Dockerfile apps/web --build-arg BUILDKIT_INLINE_CACHE=1
      - docker push localhost:5000/snapit-web:${TAG}

  - name: deploy
    image: docker
    environment:
      API_ENV_FILE:
        from_secret: API_ENV_FILE
      WEB_ENV_FILE:
        from_secret: WEB_ENV_FILE
    commands:
      - export TAG=${DRONE_COMMIT_SHA}
      - sed -i "s|snapit-api:latest|snapit-api:${TAG}|g" infra/docker-compose.yml
      - sed -i "s|snapit-web:latest|snapit-web:${TAG}|g" infra/docker-compose.yml
      - docker-compose -f infra/docker-compose.yml pull
      - docker-compose -f infra/docker-compose.yml up -d --remove-orphans

services:
  - name: docker
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
