/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * API description
 * OpenAPI spec version: 1.0
 */

import { customFetch } from ".././mutator";
import type {
  HealthControllerCheckLiveness200,
  HealthControllerCheckLiveness503,
} from "../myAPI.schemas";

export type healthControllerCheckLivenessResponse200 = {
  data: HealthControllerCheckLiveness200;
  status: 200;
};

export type healthControllerCheckLivenessResponse503 = {
  data: HealthControllerCheckLiveness503;
  status: 503;
};

export type healthControllerCheckLivenessResponseSuccess =
  healthControllerCheckLivenessResponse200 & {
    headers: Headers;
  };
export type healthControllerCheckLivenessResponseError =
  healthControllerCheckLivenessResponse503 & {
    headers: Headers;
  };

export type healthControllerCheckLivenessResponse =
  | healthControllerCheckLivenessResponseSuccess
  | healthControllerCheckLivenessResponseError;

export const getHealthControllerCheckLivenessUrl = () => "/api/health";

export const healthControllerCheckLiveness = async (
  options?: RequestInit
): Promise<healthControllerCheckLivenessResponse> =>
  customFetch<healthControllerCheckLivenessResponse>(
    getHealthControllerCheckLivenessUrl(),
    {
      ...options,
      method: "GET",
    }
  );
