/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * API description
 * OpenAPI spec version: 1.0
 */
import { customFetch } from ".././mutator";

export type prometheusControllerIndexResponse200 = {
  data: void;
  status: 200;
};

export type prometheusControllerIndexResponseSuccess =
  prometheusControllerIndexResponse200 & {
    headers: Headers;
  };

export type prometheusControllerIndexResponse =
  prometheusControllerIndexResponseSuccess;

export const getPrometheusControllerIndexUrl = () => "/api/metrics";

export const prometheusControllerIndex = async (
  options?: RequestInit
): Promise<prometheusControllerIndexResponse> =>
  customFetch<prometheusControllerIndexResponse>(
    getPrometheusControllerIndexUrl(),
    {
      ...options,
      method: "GET",
    }
  );
