# ================================
# Web Workflow
# Triggers: Changes to Web app or SDK
# ================================

when:
  - event: [push, pull_request]
    branch: master
    path:
      include:
        - "apps/web/**"
        - "packages/sdk/**"
        - "pnpm-lock.yaml"
        - "package.json"
        - ".woodpecker/web.yml"

steps:
  # ================================
  # Install Dependencies
  # ================================
  - name: install-dependencies
    image: node:22
    commands:
      - corepack enable
      - corepack prepare pnpm@latest --activate
      - pnpm install --frozen-lockfile
    environment:
      HUSKY: 0
      CI: true

  # ================================
  # Build Docker Image
  # ================================
  - name: build-image
    image: docker:27-cli
    when:
      - event: push
        branch: master
    environment:
      WEB_ENV_FILE:
        from_secret: WEB_ENV_FILE
      REGISTRY_USERNAME:
        from_secret: REGISTRY_USERNAME
      REGISTRY_PASSWORD:
        from_secret: REGISTRY_PASSWORD
      REGISTRY_URL:
        from_secret: REGISTRY_URL
    commands:
      - echo "$${WEB_ENV_FILE}" > .env.build
      - export $(cat .env.build | xargs)
      - echo "$REGISTRY_PASSWORD" | docker login $REGISTRY_URL -u "$REGISTRY_USERNAME" --password-stdin
      - export DOCKER_BUILDKIT=1
      - |
        BUILD_ARGS=""
        while IFS='=' read -r key value; do
          # Skip empty lines and comments
          [ -z "$key" ] && continue
          echo "$key" | grep -q "^#" && continue
          BUILD_ARGS="$BUILD_ARGS --build-arg $key"
        done < .env.build
        docker build \
          --file apps/web/Dockerfile \
          --build-arg NODE_VERSION=22 \
          $BUILD_ARGS \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --cache-from $REGISTRY_URL/snapit-web:latest \
          -t $REGISTRY_URL/snapit-web:latest \
          -t $REGISTRY_URL/snapit-web:${CI_COMMIT_SHA:0:8} \
          .
      - docker logout $REGISTRY_URL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - install-dependencies

  # ================================
  # Push Docker Image
  # ================================
  - name: push-image
    image: docker:27-cli
    when:
      - event: push
        branch: master
    environment:
      REGISTRY_USERNAME:
        from_secret: REGISTRY_USERNAME
      REGISTRY_PASSWORD:
        from_secret: REGISTRY_PASSWORD
      REGISTRY_URL:
        from_secret: REGISTRY_URL
    commands:
      - echo "$REGISTRY_PASSWORD" | docker login $REGISTRY_URL -u "$REGISTRY_USERNAME" --password-stdin
      - docker push $REGISTRY_URL/snapit-web:latest
      - docker push $REGISTRY_URL/snapit-web:${CI_COMMIT_SHA:0:8}
      - docker logout $REGISTRY_URL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - build-image

  # ================================
  # Deploy Web with Docker Compose
  # ================================
  - name: deploy
    image: docker:27-cli
    when:
      - event: push
        branch: master
    environment:
      INFRA_ENV_FILE:
        from_secret: INFRA_ENV_FILE
      REGISTRY_USERNAME:
        from_secret: REGISTRY_USERNAME
      REGISTRY_PASSWORD:
        from_secret: REGISTRY_PASSWORD
      REGISTRY_URL:
        from_secret: REGISTRY_URL
      WEB_VERSION: latest
    commands:
      - mkdir -p apps/api # temp
      - echo "" > apps/api/.env # temp
      - mkdir -p apps/resolver # temp
      - echo "" > apps/resolver/.env # temp

      - echo "$${INFRA_ENV_FILE}" > .env
      - echo "$REGISTRY_PASSWORD" | docker login $REGISTRY_URL -u "$REGISTRY_USERNAME" --password-stdin
      - docker pull $REGISTRY_URL/snapit-web:latest
      - docker compose up -d snapit-web --remove-orphans
      - docker image prune -af --filter "until=72h"
      - docker compose ps
      - docker logout $REGISTRY_URL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - push-image
