/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * API description
 * OpenAPI spec version: 1.0
 */

import { customFetch } from ".././mutator";
import type { CreateUrlDto, UrlDto } from "../myAPI.schemas";

export type urlsControllerCreateUrlResponse201 = {
  data: UrlDto;
  status: 201;
};

export type urlsControllerCreateUrlResponseSuccess =
  urlsControllerCreateUrlResponse201 & {
    headers: Headers;
  };

export type urlsControllerCreateUrlResponse =
  urlsControllerCreateUrlResponseSuccess;

export const getUrlsControllerCreateUrlUrl = () => "/api/urls";

export const urlsControllerCreateUrl = async (
  createUrlDto: CreateUrlDto,
  options?: RequestInit
): Promise<urlsControllerCreateUrlResponse> =>
  customFetch<urlsControllerCreateUrlResponse>(
    getUrlsControllerCreateUrlUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(createUrlDto),
    }
  );
